export const GET_MEALS = 'GET_MEALS';
export const ADD_MEAL = 'ADD_MEAL';
export const SET_MEAL = 'SET_MEAL';
export const EDIT_MEAL = 'EDIT_MEAL';
export const DELETE_MEAL = 'DELETE_MEAL';
export const SEARCH_MEALS = 'SEARCH_MEALS';
export const SET_MEALS_LOADING = 'SET_MEALS_LOADING';
export const EMPTY_MEALS = 'EMPTY_MEALS';

export const USER_LOADED = 'USER_LOADED';
export const USER_LOADING = 'USER_LOADING';
export const AUTH_ERROR = 'AUTH_ERROR';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const TOGGLE_ITEM_MENU = 'TOGGLE_ITEM_MENU';
export const TOGGLE_SIGNUP_MENU = 'TOGGLE_SIGNUP_MENU';
export const TOGGLE_LOGIN_MENU = 'TOGGLE_LOGIN_MENU';

export const SET_ACTIVE_FILTERS = 'SET_ACTIVE_FILTERS';
export const RESET_ACTIVE_FILTERS = 'RESET_ACTIVE_FILTERS';
export const BUILD_FILTERS = 'BUILD_FILTERS';

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';